using Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace UnitTests.AuthServices
{
    // Code generated by AI
    public class TestHelper
    {
        public static RefreshToken NewRt(int userId, int sessionId, string token = "rt-token", bool isActive = true) =>
            new RefreshToken
            {
                UserId = userId,
                SessionId = sessionId,
                Token = token,
                ExpiresAtUtc = DateTime.UtcNow.AddDays(7),
                RevokedAtUtc = isActive ? (DateTime?)null : DateTime.UtcNow.AddMinutes(-1)
            };

        public static Data.Entities.User NewUser(int id, string email, string username, bool active = true) =>
            new Data.Entities.User
            {
                Id = id,
                Email = email,
                Username = username,
                IsActive = active,
                PasswordHash = "hash",
                CreatedAt = DateTime.UtcNow,
                Role = Domain.Enums.Role.SHOPPER
            };
    }
}
