version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: myapp-postgres
    environment:
      POSTGRES_DB: techtrend_db
      POSTGRES_USER: techtrend_user
      POSTGRES_PASSWORD: TechTrendPass123
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myapp -d myapp_db"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  pgdata:
