using Application.Abstraction;
using Application.Abstractions;
using Application.Dtos.Cart;
using Application.Exceptions;
using Application.Services.Implementations;
using Data.Entities;
using Domain.Enums;
using Microsoft.Extensions.Configuration;
using NSubstitute;
using System.Linq.Expressions;

namespace UnitTests.CartServices
{
    // Code generated by AI
    public class CheckoutAsyncTest
    {
        private readonly ICartRepository _cartRepository = Substitute.For<ICartRepository>();
        private readonly IProductRepository _productRepository = Substitute.For<IProductRepository>();
        private readonly ICouponRepository _couponRepository = Substitute.For<ICouponRepository>();
        private readonly IInventoryRepository _inventoryRepository = Substitute.For<IInventoryRepository>();
        private readonly IUnitOfWork _uow = Substitute.For<IUnitOfWork>();
        private readonly IConfiguration _config;
        private readonly CartService _service;

        public CheckoutAsyncTest()
        {
            var inMemory = new[]
            {
                new KeyValuePair<string,string>("Payments:Simulation:SuccessRatePercent","100")
            };
            _config = new ConfigurationBuilder()
                .AddInMemoryCollection(inMemory)
                .Build();

            TestHelper.SetupTransactionPassthrough(_uow);

            _service = new CartService(_config, _cartRepository, _productRepository, _couponRepository, _inventoryRepository, _uow);
        }

        private static Product MakeProduct(int id, decimal price, string title = "P") =>
            new Product { Id = id, Title = title, Price = price };

        private static CheckoutRequest Req(string address = "ADDR", PaymentMethod method = PaymentMethod.CREDIT_CARD) =>
            new CheckoutRequest { Address = address, PaymentMethod = method };

        [Fact]
        public async Task Checkout_Approved_DecrementsInventory_PlacesOrder_AndCreatesNewCart()
        {
            // Arrange
            const int userId = 7;
            const int prodId = 101;
            var cart = TestHelper.CartWithItem(userId, prodId, qty: 2);
            cart.Status = CartStatus.ACTIVE;

            _cartRepository.GetByUserIdAsync(userId, includeGraph: true, Arg.Any<CancellationToken>())
                           .Returns(cart);

            _productRepository.GetByIdAsync(Arg.Any<CancellationToken>(), prodId)
                              .Returns(MakeProduct(prodId, price: 10m));

            _inventoryRepository.ListAsync(
                Arg.Any<Expression<Func<Inventory, bool>>>(), 0, 1, Arg.Any<CancellationToken>())
                .Returns(ci => new[] { TestHelper.Inv(prodId, available: 5) }.ToList());

            _cartRepository.CreateForUserAsync(userId, Arg.Any<CancellationToken>())
                           .Returns(Task.FromResult(TestHelper.EmptyCart(userId, cartId: 2)));

            SetSuccessRate(100);

            // Act
            await _service.CheckoutAsync(userId, Req());

            // Assert 
            Assert.Equal(CartStatus.PLACED, cart.Status);
            Assert.Equal(PaymentStatus.APPROVED, cart.PaymentStatus);
            Assert.Equal(20m, cart.TotalAmount); 
            Assert.Equal("ADDR", cart.Address);
            Assert.Equal(PaymentMethod.CREDIT_CARD, cart.PaymentMethod);
            Assert.NotNull(cart.PlacedAtUtc);
            Assert.NotNull(cart.PaidAtUtc);
            Assert.Null(cart.CouponId);

            await _uow.Received(1).SaveChangesAsync(Arg.Any<CancellationToken>());
            await _cartRepository.Received(1).CreateForUserAsync(userId, Arg.Any<CancellationToken>());

            _inventoryRepository.Received()
                .Update(Arg.Is<Inventory>(i => i.ProductId == prodId && i.Available == 3));
        }

        [Fact]
        public async Task Checkout_Rejected_DoesNotDecrementInventory_ButPlacesOrder_AndCreatesNewCart()
        {
            // Arrange
            const int userId = 88;
            const int prodId = 202;
            var cart = TestHelper.CartWithItem(userId, prodId, qty: 3);
            cart.Status = CartStatus.ACTIVE;

            _cartRepository.GetByUserIdAsync(userId, includeGraph: true, Arg.Any<CancellationToken>())
                           .Returns(cart);

            _productRepository.GetByIdAsync(Arg.Any<CancellationToken>(), prodId)
                              .Returns(MakeProduct(prodId, price: 5m));

            _inventoryRepository.ListAsync(
                Arg.Any<Expression<Func<Inventory, bool>>>(), 0, 1, Arg.Any<CancellationToken>())
                .Returns(ci => new[] { TestHelper.Inv(prodId, available: 100) }.ToList());

            _cartRepository.CreateForUserAsync(userId, Arg.Any<CancellationToken>())
                           .Returns(Task.FromResult(TestHelper.EmptyCart(userId, cartId: 2)));

            SetSuccessRate(0);

            // Act
            await _service.CheckoutAsync(userId, Req());

            // Assert
            Assert.Equal(CartStatus.PLACED, cart.Status);
            Assert.Equal(PaymentStatus.REJECTED, cart.PaymentStatus);
            Assert.Equal(15m, cart.TotalAmount); // 3 * 5
            Assert.Null(cart.PaidAtUtc);

            await _uow.Received(1).SaveChangesAsync(Arg.Any<CancellationToken>());
            await _cartRepository.Received(1).CreateForUserAsync(userId, Arg.Any<CancellationToken>());

            _inventoryRepository.DidNotReceive().Update(Arg.Any<Inventory>());
        }

        [Fact]
        public async Task Checkout_WhenCartNotActive_ThrowsConflictException()
        {
            // Arrange
            const int userId = 5;
            var cart = TestHelper.EmptyCart(userId);
            cart.Status = CartStatus.PLACED; 

            _cartRepository.GetByUserIdAsync(userId, includeGraph: true, Arg.Any<CancellationToken>())
                           .Returns(cart);

            // Act & Assert
            await Assert.ThrowsAsync<ConflictException>(() => _service.CheckoutAsync(userId, Req()));

            await _uow.DidNotReceive().SaveChangesAsync(Arg.Any<CancellationToken>());
            await _cartRepository.DidNotReceive().CreateForUserAsync(Arg.Any<int>(), Arg.Any<CancellationToken>());
        }

        [Fact]
        public async Task Checkout_WhenInsufficientInventory_ThrowsConflict_AndDoesNotSave()
        {
            // Arrange
            const int userId = 9;
            const int prodId = 333;
            var cart = TestHelper.CartWithItem(userId, prodId, qty: 4);
            cart.Status = CartStatus.ACTIVE;

            _cartRepository.GetByUserIdAsync(userId, includeGraph: true, Arg.Any<CancellationToken>())
                           .Returns(cart);

            _productRepository.GetByIdAsync(Arg.Any<CancellationToken>(), prodId)
                              .Returns(MakeProduct(prodId, price: 2m));

            _inventoryRepository.ListAsync(
                Arg.Any<Expression<Func<Inventory, bool>>>(), 0, 1, Arg.Any<CancellationToken>())
                .Returns(ci => new[] { TestHelper.Inv(prodId, available: 3) }.ToList()); // < qty

            SetSuccessRate(100); 

            // Act & Assert
            await Assert.ThrowsAsync<ConflictException>(() => _service.CheckoutAsync(userId, Req()));

            await _uow.DidNotReceive().SaveChangesAsync(Arg.Any<CancellationToken>());
            _inventoryRepository.DidNotReceive().Update(Arg.Any<Inventory>());
            await _cartRepository.DidNotReceive().CreateForUserAsync(Arg.Any<int>(), Arg.Any<CancellationToken>());
        }

        [Fact]
        public async Task Checkout_WhenProductNotFound_ThrowsNotFound()
        {
            // Arrange
            const int userId = 11;
            const int prodId = 444;
            var cart = TestHelper.CartWithItem(userId, prodId, qty: 1);
            cart.Status = CartStatus.ACTIVE;

            _cartRepository.GetByUserIdAsync(userId, includeGraph: true, Arg.Any<CancellationToken>())
                           .Returns(cart);

            _productRepository.GetByIdAsync(Arg.Any<CancellationToken>(), prodId)
                              .Returns((Product)null);

            // Act & Assert
            await Assert.ThrowsAsync<NotFoundException>(() => _service.CheckoutAsync(userId, Req()));

            await _uow.DidNotReceive().SaveChangesAsync(Arg.Any<CancellationToken>());
            await _cartRepository.DidNotReceive().CreateForUserAsync(Arg.Any<int>(), Arg.Any<CancellationToken>());
        }

        [Fact]
        public async Task Checkout_WhenInventoryNotConfigured_ThrowsNotFound()
        {
            // Arrange
            const int userId = 12;
            const int prodId = 555;
            var cart = TestHelper.CartWithItem(userId, prodId, qty: 1);
            cart.Status = CartStatus.ACTIVE;

            _cartRepository.GetByUserIdAsync(userId, includeGraph: true, Arg.Any<CancellationToken>())
                           .Returns(cart);

            _productRepository.GetByIdAsync(Arg.Any<CancellationToken>(), prodId)
                              .Returns(MakeProduct(prodId, price: 9m));

            _inventoryRepository.ListAsync(
                Arg.Any<Expression<Func<Inventory, bool>>>(), 0, 1, Arg.Any<CancellationToken>())
                .Returns(ci => Enumerable.Empty<Inventory>().ToList());

            SetSuccessRate(100);

            // Act & Assert
            await Assert.ThrowsAsync<NotFoundException>(() => _service.CheckoutAsync(userId, Req()));

            await _uow.DidNotReceive().SaveChangesAsync(Arg.Any<CancellationToken>());
            await _cartRepository.DidNotReceive().CreateForUserAsync(Arg.Any<int>(), Arg.Any<CancellationToken>());
        }

        private void SetSuccessRate(int percent)
        {
            (_config as IConfigurationRoot)!.Providers.First()
                .Set("Payments:Simulation:SuccessRatePercent", percent.ToString());
        }
    }
}
