using Application.Abstraction;
using Application.Abstractions;
using NSubstitute;
using Application.Services.Implementations;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.Extensions.Configuration;

namespace UnitTests.CartServices
{
    // Code generated by AI
    public class RemoveItemAsyncTest
    {
        private readonly IConfiguration _config = Substitute.For<IConfiguration>();
        private readonly ICartRepository _cartRepo = Substitute.For<ICartRepository>();
        private readonly IProductRepository _productRepo = Substitute.For<IProductRepository>();
        private readonly ICouponRepository _couponRepo = Substitute.For<ICouponRepository>();
        private readonly IInventoryRepository _inventoryRepo = Substitute.For<IInventoryRepository>();
        private readonly IUnitOfWork _uow = Substitute.For<IUnitOfWork>();
        private readonly CartService _sut;

        public RemoveItemAsyncTest()
        {
            _sut = new CartService(_config, _cartRepo, _productRepo, _couponRepo, _inventoryRepo, _uow);
        }

        [Fact]
        public async Task RemoveItemAsync_Removes_WhenExists()
        {
            var ct = CancellationToken.None;
            int userId = 1, productId = 10;
            var initial = TestHelper.CartWithItem(userId, productId, 2, 3);
            var reloaded = TestHelper.EmptyCart(userId, 3);

            _cartRepo.GetByUserIdAsync(userId, true, ct).Returns(initial, reloaded);
            _uow.SaveChangesAsync(ct).Returns(1);

            var res = await _sut.RemoveItemAsync(userId, productId, ct);

            Assert.Empty(res.Items);
            await _uow.Received(1).SaveChangesAsync(ct);
        }

        [Fact]
        public async Task RemoveItemAsync_DoesNothing_WhenItemMissing()
        {
            var ct = CancellationToken.None;
            int userId = 1, productId = 999;
            var initial = TestHelper.EmptyCart(userId, 3);
            var reloaded = initial;

            _cartRepo.GetByUserIdAsync(userId, true, ct).Returns(initial, reloaded);
            _uow.SaveChangesAsync(ct).Returns(1);

            var res = await _sut.RemoveItemAsync(userId, productId, ct);

            Assert.Empty(res.Items);
            await _uow.Received(1).SaveChangesAsync(ct);
        }
    }
}
